version: "3.9"

services:
  testing:
    image: olobatonnova/pan-container:latest
    environment:
      API_REST: "http://backend:3000/api/"
    depends_on:
      - backend
    ports:
      - "3636:3636"
    networks:
      - testing_network
    volumes:
      - type: bind
        source: ./evidence
        target: /my-cypress-project/cypress/screenshots/

  backend:
    image: olobatonnova/nodejs-testing:latest
    networks:
      - testing_network
    ports:
      - "3000-3010:3000"

networks:
  testing_network:



